name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:
  workflow_run:
    workflows:
      - Build SIPSsert Image
    types:
      - completed
  schedule:
    - cron: '0 2 * * Mon'
  workflow_call:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      with:
        repository: man1207/sipssert-opensips-tests
        ref: feature/junit
        path: tests

    - name: Read and parse YAML file
      id: set-matrix
      uses: man1207/SIPssert/.github/actions/Set_Matrix@feature/junit

  test:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}

    steps:

    - name: Prepare SIPssert
      uses: man1207/SIPssert/.github/actions/Prepare_SIPssert@feature/junit
      with:
        sipssert-repo: man1207/SIPSsert
        tests-repo: man1207/sipssert-opensips-tests

    - name: Run Test
      uses: man1207/SIPssert/.github/actions/Run_Tests@feature/junit
      with:
        tests: ${{ matrix.tests }}
